// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPbbA_dxOSfg9awAeGR5vO0qqfUS54M88',
    appId: '1:883900664240:web:91769690a03238f5c16e75',
    messagingSenderId: '883900664240',
    projectId: 'flutterfire-384ef',
    authDomain: 'flutterfire-384ef.firebaseapp.com',
    storageBucket: 'flutterfire-384ef.appspot.com',
    measurementId: 'G-4ZZSHNJNYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWjRtAbAbvnwOQdtCIWYlbWh7sAG_z9-0',
    appId: '1:883900664240:android:593d75935950e77ec16e75',
    messagingSenderId: '883900664240',
    projectId: 'flutterfire-384ef',
    storageBucket: 'flutterfire-384ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAllaJ_quS9uQ24XM7PGFGcCBasTYrAfL4',
    appId: '1:883900664240:ios:9b27ff908a4bead4c16e75',
    messagingSenderId: '883900664240',
    projectId: 'flutterfire-384ef',
    storageBucket: 'flutterfire-384ef.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAllaJ_quS9uQ24XM7PGFGcCBasTYrAfL4',
    appId: '1:883900664240:ios:9b27ff908a4bead4c16e75',
    messagingSenderId: '883900664240',
    projectId: 'flutterfire-384ef',
    storageBucket: 'flutterfire-384ef.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPbbA_dxOSfg9awAeGR5vO0qqfUS54M88',
    appId: '1:883900664240:web:e4dbb563dd3f6799c16e75',
    messagingSenderId: '883900664240',
    projectId: 'flutterfire-384ef',
    authDomain: 'flutterfire-384ef.firebaseapp.com',
    storageBucket: 'flutterfire-384ef.appspot.com',
    measurementId: 'G-PTF09S863B',
  );

}